import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RizzCells. - Phone Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header>
          <Link href="/">
            <h1 className="text-4xl text-center p-4 hover:font-semibold">RizzCells.</h1>
          </Link>
        </header>
        <main className="max-w-screen-xl mx-auto">
          {children}
        </main>
        <footer className="mt-8">
          <p className="border-t-2 border-inherit text-center p-4 mt-8">© 2024 RizzCells. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
