import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RizzBella",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="max-w-screen-xl mx-auto p-6">
          <Link href="/">
            <h1 className="text-center text-3xl">
             <span>Rizz</span><span className="font-bold">Bella</span>
            </h1>
          </Link>
          <h2 className="text-center uppercase">Fullfill your bella everyday</h2>
        </header>
        <main className="max-w-screen-xl mx-auto">{children}</main>
        <footer className="text-center bg-zinc-400 py-4 mt-8">
          <p>&copy; 2024 RizzBella</p>
        </footer>
      </body>
    </html>
  );
}
